### ISSUE TITLE
Acquire content

### ISSUE THREAD

**Issue by sbeleidy** [sbeleidy/peerbots-content#31]
When user clicks the plus button they go to the content details page which now contains its own "acquire content" button. When that button is clicked the user gets a confirmation alert thingy

**Comment by ynadeem** [comment]
Additional tasks
- [ ] From content details page, if I am the author, I should be able to list private content publicly
- [ ] Content details page should list # sales & # copies next to the # reviews. This is next to the acquire content button
- [ ] Add star rating in top summary section as well as keeping it next to acquire content
- [ ] Create review scrolling mechanism: In desktop --> contained scroll section, in mobile --> carousel/wheel scrolling mechanism
- [ ] Edit content #32
