### ISSUE TITLE
Content Row and Card Styling

### ISSUE THREAD

**Issue by ynadeem** [sbeleidy/peerbots-content#47]
- [ ] Add a section in the card that hides the acquire button & rating if the card is copied content and shows what it's a copy of.
- [ ] Mobile styling

**Comment by sbeleidy** [comment]
Remove `w-full` from navbar and footer parents

**Comment by sbeleidy** [comment]
- [ ] Make content card button and read more work
- [ ] Make "copy of" version of the card that doesn't have the button and price
- [ ] Fix cursors on all the things
